### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by shrutimishra27** [harshit-sharmaaa/harshit-sharmaaa#1]
Hey @harshit-sharmaaa, you seem to be new to open source and by observing a series of event:
[issue comment](https://github.com/Vikash-8090-Yadav/Future.WebNet/issues/2#issuecomment-1576560082)
[readme-file](https://github.com/harshit-sharmaaa/harshit-sharmaaa)
I suspect you are trying to duplicate my work without my consent, I would like to inform you that duplicating someone's work without their permission is clear case of plagiarism and violation of intellectual property.
Currently its just about a comment and readme but it may go further on cloning my projects and showing up on your GitHub.
So I kindly suggest you to stop this if you are doing it because it's not appropriate, avoid doing any such things in future else GitHub itself will take actions on your account since its algorithm is like this.
If you are not intentionally doing this, great continue your work Good Luck.

**Comment by harshit-sharmaaa** [comment]
Hey @shrutimishra27 
Yes I am new to open source 
I liked your comment that's why i copied the structure of that comment ,
I've honored your request and removed the comment.
Coming to Copying your README , Its wonderful that's why i modified your README and used it ,Thanks for telling that its illegal .
Never my thought to copy someone else projects, so I won't copy your code.
If you feel cheated then i will delete my README.

**Comment by shrutimishra27** [comment]
No its alright.
Just wanted to aware you of such things and to simply protect my works, although a readme is not a big deal right now.
No personal grudges.
Good Luck on Open Source!
